apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deploy1-autoscaling
  labels:
    app  : my-k8s-application
    owner: MikhailBaloban
spec:
  selector:
    matchLabels:
     project: test3
  template:
    metadata:
      labels:
        project: test3
    spec:
      containers:
        - name : site-test3
          image: httpd:latest
          ports:
            - containerPort: 80
            
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion : apps/v1
    kind: Deployment
    name: my-deploy1-autoscaling
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50   
  