apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deploy1
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
     project: test1
  template:
    metadata:
      labels:
        project: test1
    spec:
      containers:
        - name : site-test1
          image: nginx:latest
          ports:
            - containerPort: 80