apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deploy-2
  labels:
    app  : my-k8s-apps
spec:
  replicas: 3
  selector:
    matchLabels:
     project: test1
  template:
    metadata:
      labels:
        project: test1
    spec:
      containers:
        - name : web-test1
          image: nginx:latest
          ports:
            - containerPort: 80
        - name : web-site-test1
          image: tomcat:latest
          ports:
            - containerPort: 8080
  
  ---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-serice
  labels:
    owner: MikhailBalaban
spec:
  type: LoadBalancer
  selector:
    project: test1
  ports:
    - name: web-test1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-site-test1
      protocol: TCP
      port: 8888
      targetPort: 8080